"""Initial schema

Revision ID: 754150c42088
Revises:
Create Date: 2026-04-09 16:53:04.159998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754150c42088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import fastapi_users_db_sqlalchemy

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('latex_definition', sa.String(), nullable=True),
    sa.Column('complexity_class', sa.String(), nullable=True),
    sa.Column('is_assumption', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'published', 'archived', name='problemstatusenum'), nullable=True),
    sa.Column('current_runtime', sa.String(), nullable=True),
    sa.Column('io_schema', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_slug'), 'problem', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('guest', 'contributor', 'editor', 'curator', name='roleenum'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('content_version',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('problem', 'reduction', name='entitytypeenum'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatusenum'), nullable=True),
    sa.Column('curator_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reduction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('deterministic', 'randomized', name='reductiontypeenum'), nullable=True),
    sa.Column('technique', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'published', 'archived', name='reductionstatusenum'), nullable=True),
    sa.Column('runtime_relation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reduction')
    op.drop_table('content_version')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_problem_slug'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
